#!/bin/false
# shellcheck shell=sh # Written to be POSIX-compatible
# shellcheck source=src/bin/00-server-setup.sh

# Created by Jacob Hrbek under All Rights Reserved in 19/07/2020 (prepared for four freedom respecting license)

###! Workflow used to set up secret files

# FIXME-SECURITY: ps -ef  lists all processes, incluing commands with their arguments which may include our printf with 'yourpassword'

# FIXME: Ugly printf that requries a duplicate string
setup_secret() { funcname="setup_secret"
	"$CAT" <<-EOF > "/etc/auth/$DOMAIN/passwd"
		# WARNING-DO_NOT_EDIT: Autogenerated file by $UPSTREAM
		kreyren@rixotstudio.cz:$("$PRINTF" '%s\n' "$("$PRINTF" "$KEEPASS_PASSWORD\\n" | keepassxc-cli show --show-protected "$HOME/Kreyren.kdbx" 'Kreyren/dreamon' 2>/dev/null | grep 'Password:' | sed 's/Password: //')" "$("$PRINTF" "$KEEPASS_PASSWORD\\n" | keepassxc-cli show --show-protected "$HOME/Kreyren.kdbx" 'Kreyren/dreamon' 2>/dev/null | grep 'Password:' | sed 's/Password: //')" | doveadm pw -s SHA512-CRYPT):1000:1000:
		david.kosecky@rixotstudio.cz:$("$PRINTF" '%s\n' "$("$PRINTF" "$KEEPASS_PASSWORD\\n" | keepassxc-cli show --show-protected "$HOME/Kreyren.kdbx" 'DK/Email at rixotstudio.cz' 2>/dev/null | grep 'Password:' | sed 's/Password: //')" "$("$PRINTF" "$KEEPASS_PASSWORD\\n" | keepassxc-cli show --show-protected "$HOME/Kreyren.kdbx" 'Kreyren/dreamon' 2>/dev/null | grep 'Password:' | sed 's/Password: //')" | doveadm pw -s SHA512-CRYPT):::
	EOF

	funcname="$myName"
	return 0
}
